### ISSUE TITLE
Rayfield is detected.

### ISSUE THREAD

**Issue by FortniBloxYT1** [SiriusSoftwareLtd/Rayfield#11]
Rayfield and fluent, idk if more, are detected in the game dragon soul and i cant continue to make the hub for obvious reasons, first i tried fluent then rayfield because fluent was detected and rayfield is too, after like a minute of loading up the UI you get banned, no even need to create UI Components, just creating a window.

**Comment by FortniBloxYT1** [comment]
you should fix this not only for dragon soul but for more games that will detect it

**Comment by shlexware** [comment]
please message us on discord @ https://sirius.menu/discord
dm me privately after joining: @shlexr

**Comment by FortniBloxYT1** [comment]
i just dmed you
