### ISSUE TITLE
Obfuscated 3rd party code made by known malicious actor introduces major security risk

### ISSUE THREAD

**Issue by Damian-11** [SiriusSoftwareLtd/Rayfield#12]
@shlexware
While working on a bug fix, I noticed this code on line 562:
```
local function getIcon(name : string)
	-- full credit to latte softworks :)
	local iconData = not useStudio and game:HttpGet('https://raw.githubusercontent.com/latte-soft/lucide-roblox/refs/heads/master/lib/Icons.luau')
	local icons = useStudio and require(script.Parent.icons) or loadstring(iconData)()

```
This function fetches and executes obfuscated code from the following URL: https://raw.githubusercontent.com/latte-soft/lucide-roblox/refs/heads/master/lib/Icons.luau

Why does this function load obfuscated 3rd party code made by Latte Softworks—a group notorious for sharing malicious code in this scene? It should be removed ASAP, as it is a major security risk to everyone using this library. I am glad I spotted this before updating my fork, but the fact that it was put here in the first place makes me raise an eyebrow.

For context, below are some tweets showcasing previous shenanigans by this "Latte softworks" group:
![image](https://github.com/user-attachments/assets/4f020543-fc60-4059-b530-5b9366604e45)
![image](https://github.com/user-attachments/assets/30ec52ed-2d0e-46f9-9949-4b272480c27a)

**Comment by shlexware** [comment]
Thanks for voicing your concern, we have since resolved this issue in a recent update.
We would also like to note that the code you linked is not obfuscated and is just a table.

Thanks.

**Comment by Damian-11** [comment]
> Thanks for voicing your concern, we have since resolved this issue in a recent update.
> We would also like to note that the code you linked is not obfuscated and is just a table.
> 
> Thanks.

Thank you for the quick response. Any 3rd party code should always be manually vetted and forked to guarantee safety. 👍
