### ISSUE TITLE
Main window gets trapped in the top when unminimizing

### ISSUE THREAD

**Issue by Damian-11** [SiriusSoftwareLtd/Rayfield#3]
https://github.com/user-attachments/assets/19a15d0b-9e57-4b9f-b485-80bd37a5910e

If you unminimize the window while it is at the upper part of your screen, you won't be able to pull it down or close it. The only way to recover from this is by rejoining the game or re-executing the script.

A quick check to ensure that the window does not extend above the top of the screen when the minimize button is pressed should be enough to resolve this.

**Comment by shlexware** [comment]
Working on a fix for this

**Comment by Bloxnite** [comment]
u can just press k..

**Comment by Damian-11** [comment]
> u can just press k..

That only hides the UI; it'll still be stuck at the top of the screen when I unhide it. The position doesn't change, and it doesn't let me drag it back down.

**Comment by shlexware** [comment]
This has been fixed in an update this month. There is now a natural drag bar below Rayfield.
